### PR TITLE
add ruby version file

### PR DESCRIPTION
**Pull request by edap**
If the ruby version is specified in the README, and if the application
is built to work with a certain version of Ruby, the .ruby-version file
should be checked out in the repository

### CODE REVIEW

**Comment by jamezilla** [comment]
This is perhaps a bit old school, but the ruby version is specified in the Gemfile. Things could stand to be modernized a bit, for sure.

**Comment by edap** [comment]
Yes, that the ruby version specified in the gemfile should be consistent with that one in .ruby-version.
Ruby version is a file read by rbenv. I have added it because rbenv is the de facto way to install ruby, and if we are hoping to have also new comers on board for this project, we should also have a look to make things easier for getting started.

**Comment by edap** [comment]
Are there any news on this front?

**Comment by jamezilla** [comment]
Apologies I left this mouldering for so long. I guess I bumped the ruby version a while back so this PR is no longer applicable.

A `.ruby-version` file has been added to the current repo.

**Pull request closed without merging**
